name: DS5111 Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python runtime
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pipeline dependencies
      run: |
        make update

    - name: Lint codebase with Pylint
      run: |
        make lint

    - name: Execute automated test suite with Pytest
      run: |
        make test
